# Generated by Django 3.2.6 on 2021-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/Anonymous.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
